# Generated by Django 5.1.4 on 2026-05-26 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lekarz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pwz', models.CharField(blank=True, max_length=7, null=True, unique=True)),
                ('miejsce_pracy', models.CharField(blank=True, max_length=200)),
                ('specjalizacja', models.CharField(blank=True, max_length=100)),
                ('telefon', models.CharField(blank=True, max_length=20)),
                ('uzytkownik', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lekarz',
                'verbose_name_plural': 'Lekarze',
            },
        ),
        migrations.CreateModel(
            name='Pacjentka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pesel', models.CharField(max_length=11, unique=True)),
                ('data_urodzenia', models.DateField()),
                ('przewidywana_data_porodu', models.DateField()),
                ('telefon', models.CharField(blank=True, max_length=20)),
                ('uzytkownik', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pacjentka', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pacjentka',
                'verbose_name_plural': 'Pacjentki',
            },
        ),
        migrations.CreateModel(
            name='PlikBadan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plik', models.FileField(upload_to='badania/')),
                ('nazwa_pliku', models.CharField(max_length=255)),
                ('data_wgrania', models.DateTimeField(auto_now_add=True)),
                ('wyciagniety_tekst', models.TextField(blank=True)),
                ('opis', models.CharField(blank=True, max_length=300)),
                ('pacjentka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pliki_badan', to='monitor.pacjentka')),
            ],
            options={
                'verbose_name': 'Plik badań',
                'verbose_name_plural': 'Pliki badań',
                'ordering': ['-data_wgrania'],
            },
        ),
        migrations.CreateModel(
            name='Pomiar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(blank=True, choices=[('glukoza', 'Poziom glukozy (mg/dL)'), ('cisnienie', 'Ciśnienie krwi (mmHg)'), ('tetno', 'Tętno (uderzenia/min)')], max_length=20)),
                ('wartosc', models.FloatField()),
                ('data_pomiaru', models.DateTimeField()),
                ('samopoczucie', models.IntegerField(blank=True, choices=[(1, '😞 Bardzo złe'), (2, '😕 Złe'), (3, '😐 Średnie'), (4, '🙂 Dobre'), (5, '😊 Bardzo dobre')], null=True)),
                ('notatka', models.TextField(blank=True)),
                ('pacjentka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pomiary', to='monitor.pacjentka')),
            ],
            options={
                'verbose_name': 'Pomiar',
                'verbose_name_plural': 'Pomiary',
                'ordering': ['-data_pomiaru'],
            },
        ),
        migrations.CreateModel(
            name='Recepta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_leku', models.CharField(max_length=200)),
                ('dawkowanie', models.CharField(max_length=200)),
                ('data_wypisania', models.DateField(auto_now_add=True)),
                ('do_zrealizowania', models.BooleanField(default=True)),
                ('uwagi', models.TextField(blank=True)),
                ('lekarz', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wypisane_recepty', to='monitor.lekarz')),
                ('pacjentka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recepty', to='monitor.pacjentka')),
            ],
            options={
                'verbose_name': 'Recepta',
                'verbose_name_plural': 'Recepty',
            },
        ),
        migrations.CreateModel(
            name='WizytaLekarska',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_wizyty', models.DateTimeField()),
                ('miejsce', models.CharField(max_length=200)),
                ('specjalizacja', models.CharField(max_length=100)),
                ('notatki', models.TextField(blank=True)),
                ('odbyta', models.BooleanField(default=False)),
                ('lekarz', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wizyty_lekarza', to='monitor.lekarz')),
                ('pacjentka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wizyty', to='monitor.pacjentka')),
            ],
            options={
                'verbose_name': 'Wizyta lekarska',
                'verbose_name_plural': 'Wizyty lekarskie',
                'ordering': ['data_wizyty'],
            },
        ),
        migrations.CreateModel(
            name='PacjentkaLekarza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_dodania', models.DateTimeField(auto_now_add=True)),
                ('lekarz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moje_pacjentki', to='monitor.lekarz')),
                ('pacjentka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moi_lekarze', to='monitor.pacjentka')),
            ],
            options={
                'verbose_name': 'Pacjentka lekarza',
                'verbose_name_plural': 'Pacjentki lekarza',
                'unique_together': {('lekarz', 'pacjentka')},
            },
        ),
    ]
