# Generated by Django 5.1.4 on 2026-06-11 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lekarz',
            name='telefon',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='pomiar',
            name='typ',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
