# Generated by Django 5.1.4 on 2026-06-26 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_alter_lekarz_telefon_alter_pomiar_typ'),
    ]

    operations = [
        migrations.AddField(
            model_name='recepta',
            name='data_realizacji',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recepta',
            name='kod_recepty',
            field=models.CharField(default='000256', max_length=6, unique=True),
            preserve_default=False,
        ),
    ]
