# Generated by Django 5.1.4 on 2026-03-20 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_lekarz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lekarz',
            name='specjalizacja',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='lekarz',
            name='telefon',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
