# Generated by Django 5.1.4 on 2026-04-06 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_alter_lekarz_specjalizacja_alter_lekarz_telefon'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pacjentka',
            name='pesel',
            field=models.CharField(default=12345678911, max_length=11),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PacjentkaLekarza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_dodania', models.DateTimeField(auto_now_add=True)),
                ('lekarz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moje_pacjentki', to=settings.AUTH_USER_MODEL)),
                ('pacjentka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moi_lekarze', to='monitor.pacjentka')),
            ],
            options={
                'verbose_name': 'Pacjentka lekarza',
                'verbose_name_plural': 'Pacjentki lekarza',
                'unique_together': {('lekarz', 'pacjentka')},
            },
        ),
    ]
