# Generated by Django 5.1.4 on 2026-04-06 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_pacjentka_pesel_pacjentkalekarza'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacjentka',
            name='pesel',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
