# Generated by Django 5.1.4 on 2026-04-06 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0005_alter_pacjentka_pesel'),
    ]

    operations = [
        migrations.AddField(
            model_name='lekarz',
            name='pwz',
            field=models.CharField(blank=True, max_length=7, null=True, unique=True),
        ),
    ]
