# Generated by Django 5.1.4 on 2026-04-08 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0006_lekarz_pwz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pomiar',
            name='typ',
            field=models.CharField(choices=[('glukoza', 'Poziom glukozy (mg/dL)'), ('cisnienie_s', 'Ciśnienie skurczowe (mmHg)'), ('cisnienie_r', 'Ciśnienie rozkurczowe (mmHg)'), ('tetno', 'Tętno (uderzenia/min)')], max_length=20),
        ),
    ]
