# Generated by Django 5.1.4 on 2026-05-26 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0007_alter_pomiar_typ'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lekarz',
            name='imie',
        ),
        migrations.RemoveField(
            model_name='lekarz',
            name='nazwisko',
        ),
        migrations.AlterField(
            model_name='lekarz',
            name='miejsce_pracy',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='pomiar',
            name='typ',
            field=models.CharField(blank=True, choices=[('glukoza', 'Poziom glukozy (mg/dL)'), ('cisnienie', 'Ciśnienie krwi (mmHg)'), ('tetno', 'Tętno (uderzenia/min)')], max_length=20),
        ),
        migrations.CreateModel(
            name='PlikBadan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plik', models.FileField(upload_to='badania/')),
                ('nazwa_pliku', models.CharField(max_length=255)),
                ('data_wgrania', models.DateTimeField(auto_now_add=True)),
                ('wyciagniety_tekst', models.TextField(blank=True)),
                ('opis', models.CharField(blank=True, max_length=300)),
                ('pacjentka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pliki_badan', to='monitor.pacjentka')),
            ],
            options={
                'verbose_name': 'Plik badań',
                'verbose_name_plural': 'Pliki badań',
                'ordering': ['-data_wgrania'],
            },
        ),
    ]
